<?php
/**
 * User: Kyeongdae
 * Date: 2019-03-22
 * Time: 오후 2:43
 */

namespace classes\console\command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class InitCommand extends Command {
	protected function configure()
	{
		$this
			->setName('initialize')
			->setAliases(array('init'))
			->setDescription('command 1 description')
			->setHelp('command 1 help')
		;
	}

	protected function execute(InputInterface $input, OutputInterface $output) {
		parent::execute($input, $output); // TODO: Change the autogenerated stub
	}
}