<?php
/**
 * Bitmobile System Corp.
 * 작성자: Kyeongdae
 * 일자: 2015-03-06
 * 시간: 오후 4:59
 */

namespace classes\test;
use classes\test\selenium\ServerExecutor;
use PHPUnit_Extensions_Selenium2TestCase;
use PHPUnit_Extensions_Selenium2TestCase_WebDriverException;

/**
 * Class BitSelenium2TestCase
 *
 * @package classes\test
 */
abstract class BitSelenium2TestCase extends PHPUnit_Extensions_Selenium2TestCase {
	/** @var bool Selenium 포트 체크를 했었는지 여부 */
	private static $initialLaunch = true;
	/** @var bool Selenium이 열려 있는지 여부  */
	private static $opened = false;

	/**
	 * @throws \RuntimeException
	 * @throws \Exception
	 */
	protected function runTest() {
		$this->checkAndExecuteSelenium();
		$result =  parent::runTest(); // TODO: Change the autogenerated stub
		if($this->checkExceptionPage())
			throw new \RuntimeException('may error response');
		return $result;
	}

	/**
	 * @throws \Exception
	 */
	private final function checkAndExecuteSelenium() {
		if (self::$initialLaunch) {
			self::$initialLaunch = false;

			if($this->getHost() == 'localhost')
				self::$opened = ServerExecutor::tryExecute($this->getHost(), $this->getPort(), 3, 5);
		}

		if (!self::$opened)
			throw new \PHPUnit_Extensions_Selenium2TestCase_Exception("Selenium Closed.");
	}

	public function checkExceptionPage() {
		if( !extension_loaded('xdebug')) {
			echo '**** xdebug not installed. and html error disabled ****';
			return false;
		}


		try {
			return trim($this->byXPath('//strong[1]')->text()) == 'xdebug loaded"';
		} catch(PHPUnit_Extensions_Selenium2TestCase_WebDriverException $ex) {
			if($ex->getCode() == PHPUnit_Extensions_Selenium2TestCase_WebDriverException::NoSuchElement) {
				return false;
			}
			throw $ex;
		}
	}
}